### ISSUE TITLE
Problems with Chinese characters

### ISSUE THREAD

**Issue by 1247748612** [xtyxtyx/minio-dart#14]
There is a problem with the Chinese display, can you support Chinese

**Comment by xtyxtyx** [comment]
Can you please provide your `dart --version` and steps to reproduce the problem?
Thank you.

**Comment by 1247748612** [comment]
> Can you please provide your `dart --version` and steps to reproduce the problem?
> Thank you.

Dart version 2.10.3

Look at the picture
![image](https://user-images.githubusercontent.com/29533304/101152091-89ff4b00-365d-11eb-92e2-cf3ea93974bc.png)
![image](https://user-images.githubusercontent.com/29533304/101152242-bc10ad00-365d-11eb-900c-14ae7b46ed4a.png)

**Comment by anhthoai** [comment]
This also happen with other languages like Vietnamese, Japanese,...

**Comment by xtyxtyx** [comment]
Thanks for your feedback!
This has been fixed since `3.2.0`.

**Comment by anhthoai** [comment]
Hello. displaying and opening file is ok but for folder name there is still issue like folder name: HOME NO.01 張淮, it still say "S3 storage path is not valid". Could you please have a look?

**Comment by xtyxtyx** [comment]
Hi @anhthoai, `3.5.0` has been published with a fix on that. Does the new version of the package solve the problem you encountered?

**Comment by anhthoai** [comment]
@xtyxtyx it is working well now. Thank you so much!

**Comment by 1247748612** [comment]
Thanks！
