### ISSUE TITLE
where is incorrect? I want to upload  an image file to "amazonaws"

### ISSUE THREAD

**Issue by inshyma** [xtyxtyx/minio-dart#21]
`Future<String> minioUploadFile(
  String bucketName,
  String key,
  String endPoint,
  String accessKey,
  String secretKey,
  String sessionToken, {
  File file,
  String fileName,
  String port,
  String region,
}) async {
  assert(file != null || (fileName != null && fileName.isNotEmpty));
  final minio = Minio(
    endPoint: 's3-us-west-1.amazonaws.com',
    accessKey: accessKey,
    secretKey: secretKey,
    sessionToken: sessionToken,
    region: 'us-west-1',
    enableTrace: true,
  );
  return await minio.fPutObject(
      bucketName, key, fileName ?? file.absolute.path);
}`

**Comment by vgula** [comment]
What's the key in your fPutObject?

**Comment by inshyma** [comment]
just like "avatar/2021/01/xxxxxxxxxxxxxxxx.jpg"

**Comment by ramsmart-inno** [comment]
In the Key area, you pass a string of custom names with extension type.

Like, "my_snap.jpeg".
