### ISSUE TITLE
Nullsafety version

### ISSUE THREAD

**Issue by stargazing-dino** [xtyxtyx/minio-dart#22]
Hi !

I thought I would give a shot at turning this package to null safety but it was quickly over my head. Especially the `minio_models_generated.dart` file. Sorry. In any case, it'd be great if this library could support null safety.

Thank you for library

**Comment by dospringer** [comment]
Now with Flutter 2.0, the null safety support would be very nice :)

**Comment by allanwolski** [comment]
+1

**Comment by lijy91** [comment]
Now it is Sound null safety
