### ISSUE TITLE
How to upload files to specific folder in s3 bucket?

### ISSUE THREAD

**Issue by ramsmart-inno** [xtyxtyx/minio-dart#25]
There is a way to upload a specific folder.

**Comment by cchoi94** [comment]
You have to add the folder directory in the object param. So for example, I have a folder named 'avatars'
```
const filename = 'user-1-avatar'
const fileDir = 'avatars/${filename}'
const myImagePath = // your image path

fPutObject('my-s3-bucket', fileDir, myImagePath)
```
this will then add my file which I've named 'user-1-avatar' into my 'avatars' folder

**Comment by ramsmart-inno** [comment]
> You have to add the folder directory in the object param. So for example, I have a folder named 'avatars'
> 
> ```
> const filename = 'user-1-avatar'
> const fileDir = 'avatars/${filename}'
> const myImagePath = // your image path
> 
> fPutObject('my-s3-bucket', fileDir, myImagePath)
> ```
> 
> this will then add my file which I've named 'user-1-avatar' into my 'avatars' folder

Really helpful, Thank you mate @cchoi94 all is well.
