### ISSUE TITLE
Incompatibility with Flutter 2.0.0 SDK

### ISSUE THREAD

**Issue by daniarmas** [xtyxtyx/minio-dart#26]
Because every version of minio depends on intl ^0.16.1 and every version of flutter_localizations from sdk depends on intl 0.17.0, minio is incompatible with flutter_localizations from sdk.

**Comment by allanwolski** [comment]
+1

**Comment by lijy91** [comment]
Resolved, please update to [`v3.5.1`](https://pub.dev/packages/minio/changelog#351)
