### ISSUE TITLE
Files with symbols in name cause an AWS signature error

### ISSUE THREAD

**Issue by HexaJohn** [xtyxtyx/minio-dart#29]
**Issue**
Filenames containing any of these symbols !@$&()=+; cause AWS to return an error: 
`SignatureDoesNotMatch
"The request signature we calculated does not match the signature you provided. Check your key and signing method."`

This is problematic because filenames such as "Image (Copy).png" are quite common on desktop OS's.

Files containing ~`[]{}#%^-_ in the name don't seem to affect the signature.

**To Reproduce:**
Specify an AWS S3 endpoint and bucket. Initiate an fPutObject request to upload a file containing one of the problematic symbols in the name. The response from Amazon will be `"SignatureDoesNotMatch"`. Using minio: ^2.0.0-pre for testing.

**Comment by xtyxtyx** [comment]
Fixed in `3.0.0`.
