### ISSUE TITLE
Null safety update ?

### ISSUE THREAD

**Issue by slfhstr** [xtyxtyx/minio-dart#30]
Just wondering if an update of null safety version of the package is likely ?
I can get a list of minio buckets and objects with current package, but not put/get an object.
I'm not clear why, but I think it is because of null safety issues.
1.3 doesn't work with my other null-safty packages and dependencies and 2.0 pre-release doesn't deliver all working functions.
Just hoping !

**Comment by xtyxtyx** [comment]
Does the problem still exist in the newest version of the package(3.3.3)?
