### ISSUE TITLE
How to upload files from Flutter web with Minio Package to S3 bucket?

### ISSUE THREAD

**Issue by ramsmart-inno** [xtyxtyx/minio-dart#32]
If anyone achieved in past. please share a code or give an example of it.

Thank You.

**Comment by jtkeyva** [comment]
yeah i keep getting errors
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: 'package:minio/src/minio.dart': Failed assertion: line 876 pos 12: 'size == null || size >= 0': is not true.

**Comment by zxl777** [comment]
+1

**Comment by ramsmart-inno** [comment]
> +1

It means !!!!!

**Comment by xtyxtyx** [comment]
I tried uploading files in Flutter web with [file_picker](https://pub.dev/packages/file_picker) and it works.

```dart
import 'package:minio/minio.dart';
import 'package:file_picker/file_picker.dart';
...
final pick = await FilePicker.platform.pickFiles();
final file = pick.files.single;
await minio.putObject(bucket, file.name, Stream.value(file.bytes!));
```

**Comment by ramsmart-inno** [comment]
> ```dart
> final pick = await FilePicker.platform.pickFiles();
> final file = pick.files.single;
> await minio.putObject(bucket, file.name, Stream.value(file.bytes!));
> ```

Really nerd id man with Minio. For flutter web. Thanks for revert man.

**Comment by BenjiFarquhar** [comment]
> I tried uploading files in Flutter web with [file_picker](https://pub.dev/packages/file_picker) and it works.
> 
> ```dart
> import 'package:minio/minio.dart';
> import 'package:file_picker/file_picker.dart';
> ...
> final pick = await FilePicker.platform.pickFiles();
> final file = pick.files.single;
> await minio.putObject(bucket, file.name, Stream.value(file.bytes!));
> ```

I got my image file by other means (image_picker and image_cropper) so `await minio.putObject(bucket, file.name, Stream.value(file.bytes!));` was all I needed as `minio.fPutObject` doesn't work on web.

**Comment by FabriceACohen** [comment]
I tried it and it doesn't work for me ! 
It push the file but end by : "XMLHttpRequest error."
