### ISSUE TITLE
listObjects is returning error

### ISSUE THREAD

**Issue by GaoWhitebird** [xtyxtyx/minio-dart#34]
listObjects is returning 403 error when folder name includes space.
If folder name is not including space "NewFolder" then it is working correctly but if it is "New Folder" then it is returning error.
Hope you to let me know the reason or solution.
Thanks.

**Comment by xtyxtyx** [comment]
Thanks for your feedback!
This has been fixed in `3.1.0` and I'm closing the issue now.

**Comment by GaoWhitebird** [comment]
Thanks very much for your help.
I tried with updated code and all are working fine, Thanks again.
