### ISSUE TITLE
Use accessKey,secretKey and sessionToken that generated by AssumeRole API to upload file, but return The security token included in the request is invalid

### ISSUE THREAD

**Issue by ggdream** [xtyxtyx/minio-dart#36]
Hello, this is my problem:
Use accessKey,secretKey and sessionToken that generated by AssumeRole API to upload file, but return The security token included in the request is invalid.

![image](https://user-images.githubusercontent.com/60403489/150463864-4d57635f-fef5-4950-96f6-e6231bf4ad4d.png)

![image](https://user-images.githubusercontent.com/60403489/150464005-5a056afd-2fb1-450c-8f0f-219352b1da56.png)

**Comment by FaKenKoala** [comment]
#44 solves the problem.

**Comment by ggdream** [comment]
Good news. Waitting for it. @FaKenKoala

**Comment by lijy91** [comment]
Resolved, please update to [`v3.5.1`](https://pub.dev/packages/minio/changelog#351)
