### ISSUE TITLE
Support for folder upload?

### ISSUE THREAD

**Issue by YYangyuan** [xtyxtyx/minio-dart#39]
The code can upload file, but is there any way to upload folders？

**Comment by YYangyuan** [comment]
Maybe i can zip the dir and upload the zip file.

**Comment by YYangyuan** [comment]
Maybe i can zip the dir and upload the zip file.

**Comment by jpetro416** [comment]
Directories are hard to upload for any language/app. Usually you need to create the new dir on the target system, iterate the current local dir and upload each file one at a time to the target system. Or you can zip -> upload -> unzip

**Comment by shvc** [comment]
S3 not support foldres, pls impl it yourself

**Comment by lijy91** [comment]
> Directories are hard to upload for any language/app. Usually you need to create the new dir on the target system, iterate the current local dir and upload each file one at a time to the target system. Or you can zip -> upload -> unzip

Good answer
