### ISSUE TITLE
minio.bucketExists is true although bucket doesn't exist

### ISSUE THREAD

**Issue by janoschp** [xtyxtyx/minio-dart#5]
This is a part of my code: 

`      final bool exists = await minio.bucketExists(userBucket);
      print('bucket exists: $exists');
      if (!exists) {
        await minio.makeBucket(userBucket);
      }
      await minio.putObject(
`

exists is true in this case and therefore when calling putObject this error gets thrown:

`[ +138 ms] [ERROR:flutter/lib/ui/ui_dart_state.cc(171)] Unhandled Exception: MinioError: The specified bucket does not exist
[        ] #0      validate (package:minio/src/minio_helpers.dart:222:5)
[        ] #1      MinioUploader.upload (package:minio/src/minio_uploader.dart:112:5)
[        ] <asynchronous suspension>
[        ] #2      MinioUploader.addStream (package:minio/src/minio_uploader.dart:48:27)
[        ] <asynchronous suspension>
[        ] #3      Stream.pipe (dart:async/stream.dart:740:27)
[        ] #4      Minio.putObject (package:minio/src/minio.dart:832:48)
`

**Comment by philenius** [comment]
@janoschpelzer from Freiburg, I created a bug fix and @xtyxtyx published a new release `1.1.0` just a few hours ago. Can you test it out? Greetings from Villingen-Schwenningen

```yaml
dependencies:
  minio: ^1.1.0
```
