### ISSUE TITLE
The AWS Access Key Id you provided does not exist in our records.

### ISSUE THREAD

**Issue by Wqleonard** [xtyxtyx/minio-dart#61]
final minio = Minio(
            region: response.options.region,
            endPoint: 's3.amazonaws.com',
            accessKey: response.options.accessKeyId,
            secretKey: response.options.secretAccessKey,
            sessionToken: response.options.sessionToken);
        try {
          String result = await minio.fPutObject(
              response.options.Bucket, response.options.Key, file.path);
          print(result);
        } catch (e) {
          print(e);
        }
Why it happen?

**Comment by lijy91** [comment]
Resolved, please update to [`v3.5.1`](https://pub.dev/packages/minio/changelog#351)
