### ISSUE TITLE
Is it finished project?

### ISSUE THREAD

**Issue by shinriyo** [xtyxtyx/minio-dart#69]
is it better?
https://github.com/agilord/aws_client

**Comment by mkbsugita** [comment]
https://pub.dev/packages/simple_s3/

**Comment by mkbsugita** [comment]
[ws_s3_upload](https://github.com/Serdnad/aws_s3_upload)
Public

**Comment by mkbsugita** [comment]
https://github.com/Serdnad/aws_s3_upload
is better
