### ISSUE TITLE
check resp.body before parse

### ISSUE THREAD

**Issue by mkbsugita** [xtyxtyx/minio-dart#71]
``` 
xml.XmlDocument.parse(resp.body);
```

S3 sometimes return HTML document. so check HTML or XML before parse.

**Comment by mkbsugita** [comment]
Use it for HTML
https://pub.dev/packages/html

**Comment by lijy91** [comment]
Resolved, please update to [`v3.5.1`](https://pub.dev/packages/minio/changelog#351)
