### ISSUE TITLE
Minio Version Solving Failed with Intl

### ISSUE THREAD

**Issue by AgnelSelvan** [xtyxtyx/minio-dart#77]
<img width="940" alt="Screen Shot 2023-05-11 at 10 56 36 AM" src="https://github.com/xtyxtyx/minio-dart/assets/47639176/4e70735c-3ff6-4585-8481-8fc75fd234a3">

After upgrading Flutter to the latest version i.e 3.10.0
In my project `flutter_localization` depends on the latest `intl` 1.18.0 
After updating `intl` to 1.18.0 Im facing an issue with this package version.

**Comment by carrasc0** [comment]
Same here, up date the dependencies please

**Comment by carrasc0** [comment]
I think think this package is discontinued

**Comment by AgnelSelvan** [comment]
Yeah, think so...

In case to fix this up, you can check out the below pull request comment and add those in ```pubspec.yaml``` file
https://github.com/xtyxtyx/minio-dart/pull/79#issuecomment-1547170516

**Comment by lijy91** [comment]
Resolved, please update to [`v3.5.1`](https://pub.dev/packages/minio/changelog#351)
