### ISSUE TITLE
Flutter 3.10 not compatible

### ISSUE THREAD

**Issue by carrasc0** [xtyxtyx/minio-dart#78]
After upgrading Flutter to the latest version i.e 3.10.0
In my project flutter_localization depends on the latest intl 1.18.0
After updating intl to 1.18.0 Im facing an issue with this package version.

**Comment by andynunes** [comment]
Also facing this issue caused by the dependency on `intl ^0.17.0`. Is there a plan to update dependencies and release soon? If not could a pull request be submitted with the appropriate updates?

**Comment by lijy91** [comment]
Resolved, please update to [`v3.5.1`](https://pub.dev/packages/minio/changelog#351)
