### ISSUE TITLE
Please Update to http ^1.0.0

### ISSUE THREAD

**Issue by mehmetemregokberk** [xtyxtyx/minio-dart#84]
Hi, 
Please update http dependency to http ^1.0.0 or above.

Thanks.

**Comment by Padi142** [comment]
bump

**Comment by tonyteo72** [comment]
Yes, pls update to use http ^1.1.0 and above. I am using this flutter package and other package upgrade required HTTP 1.1.0 and higher.

**Comment by lijy91** [comment]
Resolved, please update to [`v3.5.1`](https://pub.dev/packages/minio/changelog#351)
