### ISSUE TITLE
updated https and xml versions

### ISSUE THREAD

**Issue by mah71** [xtyxtyx/minio-dart#90]
Hi,

i was having an issue where minio package would not work with some packages specifically ones that depends on a modern version of https/xml packages (e.g http_certificate_pinning). so this means that minio_new https version depends on  ^0.13.1  which is a version lower than specified in another dependency.

for anyone having the same issue i have forked this repository and upgraded the https and xml package dependency.

you can use this in your pubspec.yaml
dependencies:
  minio:
    git:
      url: https://github.com/mah71/minio-dart.git
      ref: mah71-latest

**Comment by lijy91** [comment]
Resolved, please update to [`v3.5.1`](https://pub.dev/packages/minio/changelog#351)
